substitutions:
  device_name: "watering-pump-baf-908-00"
  friendly_name: "Watering Pump BAF-908 (00)"
  project_name: "tuya.watering-pump-baf-908"
  project_version: "1.0"

esphome:
  name: "${device_name}"
  friendly_name: ${friendly_name}
  #name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

  on_boot:
    priority: -100
    then:
      - lambda: |-
          auto temp = ESP.getResetReason();
          id( reset_reason).publish_state( temp.c_str());

esp8266:
  board: esp07s
  restore_from_flash: true

preferences:
  flash_write_interval: 1min

# Enable logging
# Levels:
#   - ERROR: ESP_LOGE
#   - WARNING: ESP_LOGW
#   - INFO: ESP_LOGI
#   - DEBUG: ESP_LOGD
#   - VERBOSE: ESP_LOGV
#   - VERY_VERBOSE: ESP_LOGVV
logger:
  level: NONE
  #esp8266_store_log_strings_in_flash: false
  baud_rate: 0
  
api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password

safe_mode:
  disabled: false
  reboot_timeout: 10min
  num_attempts: 5

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 18
  power_save_mode: LIGHT
  #use_address: 192.168.200.37
  ap: #{} # This spawns an AP with the device name and mac address with no password.
    ssid: "${device_name}"
    password: !secret wifi_ap_password

captive_portal:

# web_server:
#   port: 80
#   local: true
#   auth:
#     username: !secret web_server_username
#     password: !secret web_server_password

# Time Source
time:
  - platform: homeassistant
    id: homeassistant_time
  # - platform: sntp
  #   id: sntp_time

uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600

tuya:
# Datapoint 1:      switch (value: ON)  - Power
# Datapoint 2:      enum (value: 1)     - Mode: 0 = Schedule, 1 = Manual
# Datapoint 28:     enum (value: 0)     - Pomps: 0 = A, 1 = B, 2 = A+B
# Datapoint 48:     raw (value: 01.1E.00.00.02.00.00.00.03.00.00.00.04.00.00.00.01.00.00.00.02.00.00.00.03.00.00.00.04.00.00.00.01.00.00.00.02.00.00.00.03.00.00.00.04.00.00.00 (48))   - Schedule
# Datapoint 56:     int value (value: 0)    - Duration: 0...3600s, LCD counter range 0-1599s (000...F99)
# Datapoint 101:    int value (value: 0)    - Interval: 0...99h
# Datapoint 102:    int value (value: 0)    - Timer (countdown)
# Product:          '{"p":"abzzvtulukkwzynv","v":"4.0.0","m":2,"low":1}'
  time_id: homeassistant_time

# Soft Buttons
button:
  - platform: factory_reset
    id: reset_btn
    name: "Reset to Factory Defaults"
    entity_category: "diagnostic"
    disabled_by_default: true

  - platform: restart
    id: restart_btn
    name: "Restart"
    entity_category: "diagnostic"
    disabled_by_default: true

  - platform: safe_mode
    id: safemode_btn
    name: "Safe Mode"
    entity_category: "diagnostic"
    disabled_by_default: true

####################
#      SENSORS     #
####################
sensor:
# Diagnostic
  - platform: uptime
    name: "Uptime"
    icon: mdi:clock-start
    entity_category: "diagnostic"
    disabled_by_default: true

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal (dB)"
    icon: mdi:signal
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    disabled_by_default: true
  
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal (%)"
    icon: mdi:signal
    filters:
    - lambda: return min( max( 2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    disabled_by_default: true

# Tuya
  - platform: "tuya"
    name: "Timer"
    sensor_datapoint: 102
    icon: mdi:watering-can-outline
    unit_of_measurement: s
    disabled_by_default: true

####################
#  BINARY SENSORS  #
####################
binary_sensor:
# Diagnostic
  - platform: status
    name: "Status"
    id: connection_status
    entity_category: "diagnostic"
    #disabled_by_default: true

####################
#   TEXT SENSORS   #
####################
text_sensor:
# Diagnostic
  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip-network-outline
      entity_category: "diagnostic"

    mac_address:
      name: MAC Address
      entity_category: "diagnostic"

  - platform: template
    id: reset_reason
    name: Reset Reason
    icon: mdi:progress-question
    entity_category: "diagnostic"

####################
#      SWITCH      #
####################
switch:
  - platform: "tuya"
    name: "Power"
    switch_datapoint: 1

####################
#      SELECT      #
####################
select:
  - platform: tuya
    enum_datapoint: 2
    id: tuya_mode
    name: "Mode"
    icon: mdi:hand-back-right-outline
    optimistic: true
    options:
     0: "Schedule"
     1: "Manual"

  - platform: tuya
    enum_datapoint: 28
    id: tuya_pump
    name: "Pump"
    icon: mdi:pump
    #entity_category: config
    optimistic: true
    options:
     0: "A"
     1: "B"
     2: "A+B"

####################
#     SETTINGS     #
####################
number:
  - platform: tuya
    number_datapoint: 56
    id: tuya_duration
    name: "Duration"
    icon: mdi:timer-play-outline
    unit_of_measurement: s
    mode: box
    min_value: 0
    max_value: 1599
    step: 1

  - platform: tuya
    number_datapoint: 101
    id: tuya_interval
    name: "Interval"
    icon: mdi:timer-refresh-outline
    unit_of_measurement: h
    mode: box
    min_value: 0
    max_value: 99
    step: 1

